apiVersion: v1  
kind: PersistentVolume                   
metadata:
  name: persistencia                     
  labels:
    type: local                    
spec:
  storageClassName: persistentclass          
  capacity:
    storage: 10Gi                       
  accessModes:
    - ReadWriteOnce                      
  hostPath:
    path: "/db"                       