apiVersion: v1                         
kind: PersistentVolumeClaim           
metadata:
  name: persistencia-claim                
  labels:
    type: local
spec:
  storageClassName: persistentclass  
  accessModes: 
    - ReadWriteOnce            
  resources:
    requests:
      storage: 10Gi